### ISSUE TITLE
Implement a better cropping/perspective method

### ISSUE THREAD

**Issue by d4f5409d** [ethereal-developers/OpenScan#92]
https://github.com/danopdev/Perspective

**Comment by veejayts** [comment]
duplicate #29

**Comment by d4f5409d** [comment]
> duplicate #29 

Actually, my wording was a bit weird, but I didn't quite mean what you meant. Please check it yourself, it's not only cropping, rather this amazing foss app makes the paper like you took a photo in front of it. Magic. Like Camscanner -> I always loved it because of it and never could leave it entirely because of it.

**Comment by d4f5409d** [comment]
Could you reopen this issue?

**Comment by d4f5409d** [comment]
But you know this ain't cropping, right? It simulates a different perspective of the photo.

**Comment by d4f5409d** [comment]
It connects to cropping just a little. The project make the photos looks like you took them _in front of the paper,_ so there are _no weird distortions_. **See yourself what I mean:**

![img](https://github.com/danopdev/Perspective/blob/master/examples/screenshots/initial_perspective_small.jpg?raw=true)
![img](https://github.com/danopdev/Perspective/blob/master/examples/screenshots/auto_perspective_small.jpg?raw=true)
![img](https://github.com/danopdev/Perspective/blob/master/examples/screenshots/warped_preview_small.jpg?raw=true)
